# Generated by Django 3.1 on 2020-08-15 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('water', models.IntegerField()),
                ('salt', models.IntegerField()),
                ('first_proofing', models.DurationField(blank=True)),
                ('second_proofing', models.DurationField(blank=True)),
                ('baking_time', models.DurationField()),
                ('baking_temperature', models.IntegerField()),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100, null=True)),
                ('wholegrain', models.BooleanField(default=False)),
                ('type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlourInLeaven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(null=True)),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.flour')),
            ],
        ),
        migrations.CreateModel(
            name='Grain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Leaven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sourdough', models.IntegerField()),
                ('water', models.IntegerField()),
                ('proofing', models.DurationField(null=True)),
                ('flour', models.ManyToManyField(through='bread.FlourInLeaven', to='bread.Flour')),
            ],
        ),
        migrations.AddField(
            model_name='flourinleaven',
            name='leaven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.leaven'),
        ),
        migrations.CreateModel(
            name='FlourInBread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField()),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.bread')),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.flour')),
            ],
        ),
        migrations.AddField(
            model_name='flour',
            name='grain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bread.grain'),
        ),
        migrations.AddField(
            model_name='bread',
            name='flour_mix',
            field=models.ManyToManyField(through='bread.FlourInBread', to='bread.Flour'),
        ),
        migrations.AddField(
            model_name='bread',
            name='leaven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.leaven'),
        ),
        migrations.AddField(
            model_name='bread',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
