# Generated by Django 3.1 on 2020-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='first_proofing',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bread',
            name='second_proofing',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
