# Generated by Django 3.1 on 2020-08-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0002_auto_20200808_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flour',
            name='grain',
            field=models.ForeignKey(on_delete=models.SET('Grain Removed'), to='bread.grain'),
        ),
    ]
