# Generated by Django 3.1 on 2020-08-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0004_leaven_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
        migrations.AlterField(
            model_name='leaven',
            name='proofing',
            field=models.DurationField(null=True, verbose_name='Fermentation'),
        ),
    ]
