# Generated by Django 3.1 on 2020-08-10 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0004_auto_20200809_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flourinstarter',
            name='starter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bread.starter'),
        ),
    ]
