# Generated by Django 3.1 on 2020-08-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0005_auto_20200818_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flourinbread',
            name='grams',
            field=models.IntegerField(null=True),
        ),
    ]
