# Generated by Django 3.1 on 2020-08-19 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0007_auto_20200819_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaven',
            name='grams',
        ),
        migrations.RemoveField(
            model_name='leaven',
            name='flour',
        ),
        migrations.CreateModel(
            name='FlourInLeaven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.IntegerField(null=True)),
                ('flour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.flour')),
                ('leaven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bread.leaven')),
            ],
        ),
        migrations.AddField(
            model_name='leaven',
            name='flour',
            field=models.ManyToManyField(through='bread.FlourInLeaven', to='bread.Flour'),
        ),
    ]
