# Generated by Django 3.1 on 2020-08-26 14:10

import bread.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bread', '0009_auto_20200820_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bread',
            name='baking_time',
            field=models.DurationField(validators=[bread.models.no_negative_duration]),
        ),
    ]
